instrument_base: &instrument_base
  Descriptor: IDEX>Interstellar Dust Experiment
  TEXT: >
    The Interstellar Dust Experiment (IDEX) is a time-of-flight (TOF)
    dust impact ionization mass spectrometer on the IMAP mission that
    provides the elemental composition, speed, and mass distributions
    of interstellar dust and interplanetary dust particles. Each record
    contains the data from a single dust impact. See
    https://imap.princeton.edu/instruments/idex for more details.
  Instrument_type: Particles (space)

imap_idex_l1a_sci:
  <<: *instrument_base
  Data_type: L1A_SCI>Level-1A Science Data
  Logical_source: imap_idex_l1a_sci-1week
  Logical_source_description: IMAP Mission IDEX Instrument Level-1A Data.

imap_idex_l1a_evt:
   <<: *instrument_base
   Data_type: L1A_EVT>Level-1A Event Message Data
   Logical_source: imap_idex_l1a_evt
   Logical_source_description: IMAP Mission IDEX Instrument Level-1A Event Message Data.

imap_idex_l1a_catlst:
  <<: *instrument_base
  Data_type: L1A_CATLST>Level-1A Packet Catalog Summary Data
  Logical_source: imap_idex_l1a_catlst
  Logical_source_description: IMAP Mission IDEX Instrument Level-1A Packet Catalog Summary Data.

imap_idex_l1b_sci:
  <<: *instrument_base
  Data_type: L1B_SCI>Level-1B Science Data
  Logical_source: imap_idex_l1b_sci-1week
  Logical_source_description: IMAP Mission IDEX Instrument Level-1B Data.

imap_idex_l2a_sci:
  <<: *instrument_base
  Data_type: L2A_SCI>Level-2A Science Data
  Logical_source: imap_idex_l2a_sci-1week
  Logical_source_description: IMAP Mission IDEX Instrument Level-2A Data

imap_idex_l2b_sci:
  <<: *instrument_base
  Data_level: 2B
  Data_type: L2B_SCI>Level-2B Science Data
  Logical_source: imap_idex_l2b_sci # TODO how often?
  Logical_source_description: IMAP Mission IDEX Instrument Level-2B Data