# <=== Label Attributes ===>
# LABL_PTR_i expects VAR_TYPE of metadata with char data type.
default_attrs: &default
  # Assumed values for all variable attrs unless overwritten
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: I12
  VALIDMIN: -9223372036854775808
  VALIDMAX: 9223372036854775807
  VAR_TYPE: data
  UNITS: ' '

default_coords: &default_coords
  # Assumed values for all coordinate attrs unless overwritten
  FORMAT: F2.4  # Float with 4 digits
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  VALIDMIN: -9223372036854775808
  VALIDMAX: 9223372036854775807
  UNITS: counts

mag_support_attrs: &support_default
    <<: *default
    VAR_TYPE: support_data
    DICT_KEY: SPASE>Support>SupportQuantity:Other

mag_metadata_attrs: &metadata_default
    <<: *default
    VAR_TYPE: metadata

direction_label:
  CATDESC: Magnetic field vector data
  FIELDNAM: Magnetic Field Vector
  FORMAT: A3
  VAR_TYPE: metadata

compression_label:
  CATDESC: Compression and width
  FIELDNAM: Compression and width
  FORMAT: A2
  VAR_TYPE: metadata

raw_vector_attrs: &raw_vectors_default
  <<: *default
  CATDESC: Raw unprocessed magnetic field vector data in bytes
  DEPEND_1: direction
  LABL_PTR_1: direction_label
  FIELDNAM: Magnetic Field Vector
  FORMAT: I3

vector_attrs: &vectors_default
    <<: *default
    CATDESC: Magnetic field vectors with x y z and sensor range varying by time
    DEPEND_1: direction
    FIELDNAM: Magnetic Field
    LABL_PTR_1: direction_label
    FILLVAL: 9223372036854775807
    FORMAT: F12.5

mag_flag_attrs:
    <<: *default
    VALIDMIN: 0
    VALIDMAX: 1
    DISPLAY_TYPE: time_series
    FILLVAL: 255
    FORMAT: I1

raw_direction_attrs:
    <<: *default_coords
    CATDESC: Raw magnetic field vector binary length
    FIELDNAM: Raw magnetic field vector binary length
    LABLAXIS: Magnetic field vector directions

direction_attrs:
    <<: *default_coords
    CATDESC: Magnetic field vector
    FIELDNAM: \[xyz\] magnetic field vector
    FORMAT: I3
    VAR_TYPE: support_data
    DISPLAY_TYPE: time_series
    LABLAXIS: Magnetic field vector

compression_attrs:
  <<: *default_coords
  CATDESC: Data compression flag
  FIELDNAM: Compression
  LABLAXIS: Compressed
  FORMAT: I2
  VAR_TYPE: support_data
  VALIDMAX: 21
  VALIDMIN: 0
  DISPLAY_TYPE: no_plot

compression_flags_attrs:
  <<: *support_default
  CATDESC: Compression information per time stamp, includes a flag and the compression width
  FIELDNAM: Compression information per time stamp
  DEPEND_0: epoch
  DEPEND_1: compression
  FORMAT: I2
  VALIDMAX: 21
  VALIDMIN: 0
  LABL_PTR_1: compression_label
  DISPLAY_TYPE: no_plot

compression:
    <<: *support_default
    CATDESC: Data compression flag
    FIELDNAM: Data is compressed
    LABLAXIS: Compressed
    FILLVAL: 255
    FORMAT: I1
    VALIDMAX: 1
    VALIDMIN: 0
    DICT_KEY: SPASE>Support>SupportQuantity:InstrumentMode

compression_width:
  <<: *support_default
  CATDESC: Compression bit width
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: Compressed data bit width
  LABLAXIS: Bit width
  FILLVAL: 255
  FORMAT: I2
  UNITS: 'bits'
  VALIDMAX: 21
  VALIDMIN: 0

pri_sens:
    <<: *support_default
    CATDESC: Indicates the primary sensor. 0 is MAGo, 1 is MAGi
    FIELDNAM: Primary Sensor
    LABLAXIS: Primary Sensor
    FILLVAL: 255
    FORMAT: I1
    UNITS: ' '
    VALIDMAX: 1
    VALIDMIN: 0
    DICT_KEY: SPASE>Support>SupportQuantity:InstrumentMode

vecsec:
    <<: *support_default
    CATDESC: Vectors per second
    FIELDNAM: Vectors per second
    LABLAXIS: Vectors/sec
    FILLVAL: 0
    FORMAT: I3
    UNITS: 'Hz'
    VALIDMAX: 128
    VALIDMIN: 1
    DICT_KEY: SPASE>Support>SupportQuantity:Housekeeping

vectors:
    <<: *vectors_default
    CATDESC: Magnetic field vectors with x y z and sensor range varying by time
    FIELDNAM: Magnetic field
    LABLAXIS: Magnetic field