# TODO: add attributes for science packets

# <=== Defaults ===>
# Default values for variable attrs unless overwritten
default_attrs: &default
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FILLVAL: -9223372036854775808
  FORMAT: I12
  VALIDMIN: 0
  VALIDMAX: 9223372036854775807
  VAR_TYPE: data
  UNITS: ' '
  SCALETYP: linear

default_uint8_attrs: &default_uint8
  <<: *default
  FILLVAL: 255
  FORMAT: I3
  VALIDMIN: 0
  VALIDMAX: 255
  dtype: uint8
  DEPEND_0: sc_tick

default_uint16_attrs: &default_uint16
  <<: *default
  FILLVAL: 65535
  FORMAT: I5
  VALIDMIN: 0
  VALIDMAX: 65535
  dtype: uint16
  DEPEND_0: sc_tick

default_uint32_attrs: &default_uint32
  <<: *default
  FILLVAL: 4294967295
  FORMAT: I10
  VALIDMIN: 0
  VALIDMAX: 4294967295
  dtype: uint32

default_int64_attrs: &default_int64
  <<: *default
  FILLVAL: -9223372036854775808
  FORMAT: I20
  VALIDMIN: -9223372036854775808
  VALIDMAX: 9223372036854775807
  dtype: int64

default_int32_attrs: &default_int32
  <<: *default
  FILLVAL: -2147483648
  FORMAT: I10
  VALIDMIN: -2147483648
  VALIDMAX: 2147483647
  dtype: int32

default_float32_attrs: &default_float32
  <<: *default
  FILLVAL: .NAN
  FORMAT: F10.2
  VALIDMIN: -3.4028235e+38
  VALIDMAX: 3.4028235e+38
  dtype: float32

hk_support_attrs: &hk_support_default
  <<: *default
  DISPLAY_TYPE: no_plot
  VAR_TYPE: ignore_data

hk_default_attrs: &hk_default
  <<: *default
  VALIDMAX: 4095
  FORMAT: I4

# <=== Coordinates ===>
adc_channels:   # adc_channels is a dependency for leak_i data variable
  DISPLAY_TYPE: no_plot
  FILLVAL: -9223372036854775808
  UNITS: ' '
  SCALETYP: linear
  VALIDMIN: 0
  VALIDMAX: 63
  VAR_TYPE: metadata
  CATDESC: ADC Channel
  FIELDNAM: ADC Channel
  LABLAXIS: Channel
  FORMAT: I2

# <=== Label Attributes ===>
# LABL_PTR_i expects VAR_TYPE of metadata with char data type

adc_channels_label:
  CATDESC: Analog Digital Converter Channels
  FIELDNAM: ADC Channels
  FORMAT: A2
  VAR_TYPE: metadata


# <=== Data Variable Attributes ===>

# CCSDS header variables
version:
  <<: *default_uint8
  CATDESC: CCSDS packet version number
  FIELDNAM: CCSDS version
  VAR_TYPE: support_data

type:
  <<: *default_uint8
  CATDESC: CCSDS packet type
  FIELDNAM: CCSDS type
  VAR_TYPE: support_data

sec_hdr_flg:
  <<: *default_uint8
  CATDESC: CCSDS secondary header flag
  FIELDNAM: CCSDS secondary header flag
  VAR_TYPE: support_data

pkt_apid:
  <<: *default_uint16
  CATDESC: CCSDS application process ID
  FIELDNAM: CCSDS APID
  VAR_TYPE: support_data

seq_flgs:
  <<: *default_uint8
  CATDESC: CCSDS sequence flags
  FIELDNAM: CCSDS sequence flags
  VAR_TYPE: support_data

src_seq_ctr:
  <<: *default_uint16
  CATDESC: CCSDS source sequence counter
  FIELDNAM: CCSDS sequence counter
  VAR_TYPE: support_data

pkt_len:
  <<: *default_uint16
  CATDESC: CCSDS packet length
  FIELDNAM: CCSDS packet length
  VAR_TYPE: support_data

sc_tick:
  <<: *default_uint32
  CATDESC: CCSDS secondary header - Spacecraft Tick
  FIELDNAM: Spacecraft Tick
  VAR_TYPE: support_data


# Housekeeping variables
fsw_version_a:
  <<: *hk_support_default
  VALIDMAX: 63
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number A
  LABLAXIS: FSW A
  FORMAT: I2

fsw_version_b:
  <<: *hk_support_default
  VALIDMAX: 63
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number B
  LABLAXIS: FSW B
  FORMAT: I2

fsw_version_c:
  <<: *hk_support_default
  VALIDMAX: 63
  CATDESC: Flight Software Version Number (A.B.C bits)
  FIELDNAM: Flight Software Version Number C
  LABLAXIS: FSW C
  FORMAT: I2

num_good_cmds:
  <<: *hk_support_default
  VALIDMAX: 255
  CATDESC: Number of Good Commands
  FIELDNAM: Number of Good Commands
  LABLAXIS: Counts
  FORMAT: I3

last_good_cmd:
  <<: *hk_support_default
  VALIDMAX: 255
  CATDESC: Last Good Command
  FIELDNAM: Last Good Command
  LABLAXIS: Last cmd
  FORMAT: I3

last_good_seq_num:
  <<: *hk_support_default
  VALIDMAX: 255
  CATDESC: Last Good Sequence Number
  FIELDNAM: Last Good Sequence Number
  LABLAXIS: Last num
  FORMAT: I3

num_bad_cmds:
  <<: *hk_support_default
  VALIDMAX: 255
  CATDESC: Number of Bad Commands
  FIELDNAM: Number of Bad Commands
  LABLAXIS: Counts
  FORMAT: I3

last_bad_cmd:
  <<: *hk_support_default
  VALIDMAX: 255
  CATDESC: Last Bad Command
  FIELDNAM: Last Bad Command
  LABLAXIS: Last cmd
  FORMAT: I3

last_bad_seq_num:
  <<: *hk_support_default
  VALIDMAX: 255
  CATDESC: Last Bad Sequence Number
  FIELDNAM: Last Bad Sequence Number
  LABLAXIS: Last num
  FORMAT: I3

fee_running:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - FEE Running (1) or Reset (0)
  FIELDNAM: FEE Running (1) or Reset (0)
  LABLAXIS: State
  FORMAT: I1

mram_disabled:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - MRAM Disabled (1) or Enabled (0)
  FIELDNAM: MRAM Disabled (1) or Enabled (0)
  LABLAXIS: State
  FORMAT: I1

enable_50khz:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - 50kHz Enabled (1) or Disabled (0)
  FIELDNAM: 50kHz Enabled (1) or Disabled (0)
  LABLAXIS: State
  FORMAT: I1

enable_hvps:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - HVPS Enabled (1) or Disabled (0)
  FIELDNAM: HVPS Enabled (1) or Disabled (0)
  LABLAXIS: State
  FORMAT: I1

table_status:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - Table Status OK (1) or Error (0)
  FIELDNAM: Table Status OK (1) or Error (0)
  LABLAXIS: Status
  FORMAT: I1

heater_control:
  <<: *hk_support_default
  VALIDMAX: 2
  CATDESC: State - Heater Control (0=None, 1=Pri, 2=Sec)
  FIELDNAM: Heater Control (0=None, 1=Pri, 2=Sec)
  LABLAXIS: State
  FORMAT: I1

adc_mode:
  <<: *hk_support_default
  VALIDMAX: 3
  CATDESC: State - ADC Mode (0=quiet, 1=normal, 2=adcstim, 3=adcThreshold)
  FIELDNAM: ADC Mode (0=quiet, 1=normal, 2=adcstim, 3=adcThreshold)
  LABLAXIS: ADC mode
  FORMAT: I1

mode:
  <<: *hk_support_default
  VALIDMAX: 3
  CATDESC: State - Mode (0=Boot, 1=Maintenance, 2=Standby, 3=Science)
  FIELDNAM: Mode (0=Boot, 1=Maintenance, 2=Standby, 3=Science)
  LABLAXIS: Mode
  FORMAT: I1

dyn_thresh_lvl:
  <<: *hk_support_default
  VALIDMAX: 3
  CATDESC: Dynamic Threshold Level (0-3)
  FIELDNAM: Dynamic Threshold Level (0-3)
  LABLAXIS: Level
  FORMAT: I1

num_evnt_last_hk:
  <<: *hk_support_default
  VALIDMAX: 4294967295
  CATDESC: Number of Events Since Last HK Update
  FIELDNAM: Number of Events Since Last HK Update
  LABLAXIS: Num events
  FORMAT: I10

num_errors:
  <<: *hk_support_default
  VALIDMAX: 255
  CATDESC: Number of Errors
  FIELDNAM: Number of Errors
  LABLAXIS: Num errors
  FORMAT: I3

last_error_num:
  <<: *hk_support_default
  VALIDMAX: 255
  CATDESC: State - Last Error Number
  FIELDNAM: Last Error Number
  LABLAXIS: Error num
  FORMAT: I3

code_checksum:
  <<: *hk_support_default
  VALIDMAX: 65535
  CATDESC: Code Checksum
  FIELDNAM: Code Checksum
  LABLAXIS: Checksum
  FORMAT: I5

spin_period_short:
  <<: *hk_support_default
  VALIDMAX: 65535
  CATDESC: Spin Period Short at T=0
  FIELDNAM: Spin Period Short at T=0
  LABLAXIS: Spin period short
  FORMAT: I5

spin_period_long:
  <<: *hk_support_default
  VALIDMAX: 65535
  CATDESC: Spin Period Long at T=0
  FIELDNAM: Spin Period Long at T=0
  LABLAXIS: Spin period long
  FORMAT: I5

leak_i:
  <<: *hk_support_default
  DEPEND_1: adc_channels
  CATDESC: Leakage Current [I]
  FIELDNAM: Leakage Current [I]
  LABLAXIS: Current I
  LABEL_PTR_1: adc_channels_label
  FORMAT: I19

phasic_stat:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - Phasic Status
  FIELDNAM: Phasic Status
  LABLAXIS: Status
  FORMAT: I1

active_heater:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - Active Heater
  FIELDNAM: Active Heater
  LABLAXIS: State
  FORMAT: I1

heater_on:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - Heater On/Off
  FIELDNAM: Heater On/Off
  LABLAXIS: State
  FORMAT: I1

test_pulser_on:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - Test Pulser On/Off
  FIELDNAM: Test Pulser On/Off
  LABLAXIS: State
  FORMAT: I1

dac0_enable:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - DAC 0 Enable
  FIELDNAM: DAC 0 Enable
  LABLAXIS: State
  FORMAT: I1

dac1_enable:
  <<: *hk_support_default
  VALIDMAX: 1
  CATDESC: State - DAC 1 Enable
  FIELDNAM: DAC 1 Enable
  LABLAXIS: State
  FORMAT: I1

preamp_l234a:
  <<: *hk_default
  CATDESC: Preamp L234A
  FIELDNAM: Preamp L234A
  LABLAXIS: Preamp L234A

preamp_l1a:
  <<: *hk_default
  CATDESC: Preamp L1A
  FIELDNAM: Preamp L1A
  LABLAXIS: Preamp L1A

preamp_l1b:
  <<: *hk_default
  CATDESC: Preamp L1B
  FIELDNAM: Preamp L1B
  LABLAXIS: Preamp L1B

preamp_l234b:
  <<: *hk_default
  CATDESC: Preamp L234B
  FIELDNAM: Preamp L234B
  LABLAXIS: Preamp L234B

temp0:
  <<: *hk_default
  CATDESC: FEE LDO Regulator Mounted on the Board Next to the Low-dropout Regulator
  FIELDNAM: FEE LDO Regulator
  LABLAXIS: Temp0

temp1:
  <<: *hk_default
  CATDESC: Primary Heater Mounted on the Board Next to the Primary Heater Circuit
  FIELDNAM: Primary Heater
  LABLAXIS: Temp1

temp2:
  <<: *hk_default
  CATDESC: FEE FPGA Mounted on the Board Next to the FPGA
  FIELDNAM: FEE FPGA
  LABLAXIS: Temp2

temp3:
  <<: *hk_default
  CATDESC: Secondary Heater
  FIELDNAM: Secondary Heater
  LABLAXIS: Temp3

analog_temp:
  <<: *hk_default
  CATDESC: Chassis Temp Mounted on the Analog Board Close to Thermostats, Heaters, and Chassis
  FIELDNAM: Analog Temp
  LABLAXIS: Analog temp

hvps_temp:
  <<: *hk_default
  CATDESC: Board Temp Mounted Inside Faraday Cage in Middle of Board Near Connector Side
  FIELDNAM: Board Temp
  LABLAXIS: HVPS temp

idpu_temp:
  <<: *hk_default
  CATDESC: LDO Temp Mounted on Top of the Low-dropout Regulator
  FIELDNAM: LDO Temp
  LABLAXIS: IDPU temp

lvps_temp:
  <<: *hk_default
  CATDESC: Board Temp Mounted in the Middle of Board on Opposite Side of Hottest Component
  FIELDNAM: Board Temp
  LABLAXIS: LVPS temp

ebox_3d4vd:
  <<: *hk_default
  CATDESC: 3.4VD Ebox (Digital)
  FIELDNAM: 3.4VD Ebox (Digital)
  LABLAXIS: 3.4VD Ebox

ebox_5d1vd:
  <<: *hk_default
  CATDESC: 5.1VD Ebox (Digital)
  FIELDNAM: 5.1VD Ebox (Digital)
  LABLAXIS: 5.1VD Ebox

ebox_p12va:
  <<: *hk_default
  CATDESC: +12VA Ebox (Analog)
  FIELDNAM: +12VA Ebox (Analog)
  LABLAXIS: +12VA Ebox

ebox_m12va:
  <<: *hk_default
  CATDESC: -12VA Ebox (Analog)
  FIELDNAM: -12VA Ebox (Analog)
  LABLAXIS: -12VA Ebox

ebox_p5d7va:
  <<: *hk_default
  CATDESC: +5.7VA Ebox (Analog)
  FIELDNAM: +5.7VA Ebox (Analog)
  LABLAXIS: +5.7VA Ebox

ebox_m5d7va:
  <<: *hk_default
  CATDESC: -5.7VA Ebox (Analog)
  FIELDNAM: -5.7VA Ebox (Analog)
  LABLAXIS: -5.7VA Ebox

ref_p5v:
  <<: *hk_default
  CATDESC: +5V ref
  FIELDNAM: +5V ref
  LABLAXIS: +5V ref

l1ab_bias:
  <<: *hk_default
  CATDESC: L1A/B Bias
  FIELDNAM: L1A/B Bias
  LABLAXIS: L1A/B Bias

l2ab_bias:
  <<: *hk_default
  CATDESC: L2A/B Bias
  FIELDNAM: L2A/B Bias
  LABLAXIS: L2A/B Bias

l34a_bias:
  <<: *hk_default
  CATDESC: L3/4A Bias
  FIELDNAM: L3/4A Bias
  LABLAXIS: L3/4A Bias

l34b_bias:
  <<: *hk_default
  CATDESC: L3/4B Bias
  FIELDNAM: L3/4B Bias
  LABLAXIS: L3/4B Bias

ebox_p2d0vd:
  <<: *hk_default
  CATDESC: +2.0VD Ebox (Digital)
  FIELDNAM: +2.0VD Ebox (Digital)
  LABLAXIS: +2.0VD Ebox

