instrument_base: &instrument_base
  Descriptor: SWE>Solar Wind Electron
  TEXT: >
    The IMAP Solar Wind Electron (SWE) instrument measures the solar wind electrons
    in the heliosphere. SWE will contribute to our understanding of the acceleration
    and transport of charged particles in the heliosphere.
    SWE design and assembly is led by the Princeton Plasma Physics Laboratory. See
    https://imap.princeton.edu/instruments/swe for more details.
  Instrument_type: "Particles (space)"

imap_swe_l1a_sci:
  <<: *instrument_base
  Data_type: L1A_SCI>Level-1A Science data
  Logical_source: imap_swe_l1a_sci
  Logical_source_description: SWE Instrument Level-1A Science Data

imap_swe_l1a_hk:
  <<: *instrument_base
  Data_type: L1A_HK>Level-1A Housekeeping data
  Logical_source: imap_swe_l1a_hk
  Logical_source_description: SWE Instrument Level-1A Housekeeping Data

imap_swe_l1a_cem-raw:
  <<: *instrument_base
  Data_type: L1A_CEM-RAW>Level-1A CEM Raw data
  Logical_source: imap_swe_l1a_cem-raw
  Logical_source_description: SWE Instrument Level-1A CEM Raw Data

imap_swe_l1b_sci:
  <<: *instrument_base
  Data_type: L1B_SCI>Level-1B Science data
  Logical_source: imap_swe_l1b_sci
  Logical_source_description: SWE Instrument Level-1B Science Data

imap_swe_l2_sci:
  <<: *instrument_base
  Data_type: L2_SCI>Level-2 Science data
  Logical_source: imap_swe_l2_sci
  Logical_source_description: SWE Instrument Level-2 Science Data
