default: &default
  Descriptor:
    MAG>Magnetometer
  TEXT: >
    The IMAP magnetometer MAG consists of two vector magnetic field sensors
    which measure the magnetic field in the vicinity of the
    spacecraft. MAG will contribute to our understanding of the acceleration and transport
    of charged particles in the heliosphere, the dynamics of interplanetary shocks, and provide
    real time space weather measurements via the I-AliRT service.
    MAG design, assembly, operations, and calibration are led by Imperial
    College London. See
    https://imap.princeton.edu/spacecraft/instruments/magnetometer-mag for more details.
  Instrument_type: Magnetic Fields (space)

imap_mag_l1a_norm-raw:
    <<: *default
    Data_type: L1A_norm-raw>Level-1A raw normal rate
    Logical_source: imap_mag_l1a_norm-raw
    Logical_source_description: IMAP Mission MAG Normal Rate Instrument Level-1A Data.

imap_mag_l1a_burst-raw:
    <<: *default
    Data_type: L1A_burst-raw>Level-1A raw burst rate
    Logical_source: imap_mag_l1a_burst-raw
    Logical_source_description: IMAP Mission MAG Burst Rate Instrument Level-1A Data.

imap_mag_l1a_norm-mago:
    <<: *default
    Data_type: L1A_norm-mago>Level 1A MAGo normal rate
    Logical_source: imap_mag_l1a_norm-mago
    Logical_source_description: IMAP Mission MAGo Normal Rate Instrument Level-1A Data.

imap_mag_l1a_norm-magi:
    <<: *default
    Data_type: L1A_norm-magi>Level 1A MAGi normal rate
    Logical_source: imap_mag_l1a_norm-magi
    Logical_source_description: IMAP Mission MAGi Normal Rate Instrument Level-1A Data.

imap_mag_l1a_burst-mago:
    <<: *default
    Data_type: L1A_burst-mago>Level 1A MAGo burst rate
    Logical_source: imap_mag_l1a_burst-mago
    Logical_source_description: IMAP Mission MAGo Burst Rate Instrument Level-1A Data.

imap_mag_l1a_burst-magi:
    <<: *default
    Data_type: L1A_burst-magi>Level 1A MAGi burst rate
    Logical_source: imap_mag_l1a_burst-magi
    Logical_source_description: IMAP Mission MAGi Burst Rate Instrument Level-1A Data.

imap_mag_l1b_norm-mago:
    <<: *default
    Data_type: L1B_norm-mago>Level 1B MAGo normal rate
    Logical_source: imap_mag_l1b_norm-mago
    Logical_source_description: IMAP Mission MAGo Normal Rate Instrument Level-1B Data.

imap_mag_l1b_norm-magi:
    <<: *default
    Data_type: L1B_norm-magi>Level 1B MAGi normal rate
    Logical_source: imap_mag_l1b_norm-magi
    Logical_source_description: IMAP Mission MAGi Normal Rate Instrument Level-1B Data.

imap_mag_l1b_burst-mago:
    <<: *default
    Data_type: L1B_burst-mago>Level 1B MAGo burst rate
    Logical_source: imap_mag_l1b_burst-mago
    Logical_source_description: IMAP Mission MAGo Burst Rate Instrument Level-1B Data.

imap_mag_l1b_burst-magi:
    <<: *default
    Data_type: L1B_burst-magi>Level 1B MAGi burst rate
    Logical_source: imap_mag_l1b_burst-magi
    Logical_source_description: IMAP Mission MAGi Burst Rate Instrument Level-1B Data.

imap_mag_l1c_norm-mago:
    <<: *default
    Data_type: L1C_norm-mago>Level 1C MAGo normal rate
    Logical_source: imap_mag_l1c_norm-mago
    Logical_source_description: IMAP Mission MAGo Normal Rate Instrument Level-1C Data.

imap_mag_l1c_norm-magi:
    <<: *default
    Data_type: L1C_norm-magi>Level 1C MAGi normal rate
    Logical_source: imap_mag_l1c_norm-magi
    Logical_source_description: IMAP Mission MAGi Normal Rate Instrument Level-1C Data.

imap_mag_l2_norm-dsrf:
  <<: *default
  Data_type: L2_norm-dsrf>Level 2 normal rate data in DSRF
  Logical_source: imap_mag_l2_norm-dsrf
  Logical_source_description: IMAP Mission Normal Rate Instrument Level-2 Data in
    Despun Spacecraft Reference Frame.


imap_mag_l2_burst-dsrf:
  <<: *default
  Data_type: L2_burst-dsrf>Level 2 burst rate data in DSRF
  Logical_source: imap_mag_l2_burst-dsrf
  Logical_source_description: IMAP Mission Burst Rate Instrument Level-2 Data in
    Despun Spacecraft Reference Frame.